
# Site settings
title: Hao Chen
name: Hao Chen
subtitle:  Master
email: chen_hao_zju@zju.edu.cn
description: >
   Master
baseurl: ""
url: "https://chenhao-zju.github.io/"
github_username:  chenhao-zju
disqus_baseurl: "https://chenhao-zju.github.io/"
disqus_shortname: https-chenhao-zju-github-io
permalink: :title
google-site-verification: "EBNpnv4GiHJTmePgRajamxrYtJnc6WlqDyWUITDaSMo"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Hao Chen"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: chenhao-zju
    url: https://github.com/chenhao-zju
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Hao Chen
    url: https://www.linkedin.com/in/%E6%B5%A9-%E9%99%88-378151236/
    desc: Connect with me on LinkedIn
    share: true
